### ISSUE TITLE
Add an `init` command

### ISSUE THREAD

**Issue by val-scality** [akaoj/simpleca#6]
Do not run anything unless a configuration file is found. This configuration file can be generated with a `simpleca init`. This `init` command can also create the `root/`, `intermediates/` and `clients/` folders so the hierarchy don't have to be created on the fly if needed.
This will ensure that we won't touch anything if we're not in the right folder (i.e.: a potential future `simpleca delete` won't delete some files if we're not in the right folder).
This will also make the user feel he's in some kind of a repository which might make him more at ease.

**Comment by akaoj** [comment]
This also might be the right moment to move files in subdirectories instead of putting them all at the same level in the `intermediates/ or `clients/` folders.
